services:
  - type: web
    name: licita-ai
    env: python
    rootDir: LICITA.AI
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  - type: web
    name: montaedital
    env: python
    rootDir: MONTAEDITAL
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT